load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "common",
    srcs = [
    ],
    hdrs = [
        "logging.h",
        "status.h",
    ],
    visibility = [
        "//visibility:public",
    ],
)
